/**
 * Database types for Kakeibo Share
 *
 * - database.generated.ts: Auto-generated by `npx supabase gen types typescript --local`
 *   DO NOT edit manually. Regenerate with `npm run db:gen-types`.
 * - This file: Re-exports with overrides and helper types.
 */

export type { Json } from "./database.generated";

import type { Database as GeneratedDatabase } from "./database.generated";
import type { Json } from "./database.generated";

// Override Database to add columns/RPCs not yet in generated types
export type Database = Omit<GeneratedDatabase, "public"> & {
  public: Omit<GeneratedDatabase["public"], "Tables" | "Functions"> & {
    Tables: GeneratedDatabase["public"]["Tables"] & {
      recurring_rules: {
        Row: GeneratedDatabase["public"]["Tables"]["recurring_rules"]["Row"] & {
          start_date: string;
          end_date: string | null;
        };
        Insert: GeneratedDatabase["public"]["Tables"]["recurring_rules"]["Insert"] & {
          start_date: string;
          end_date?: string | null;
        };
        Update: GeneratedDatabase["public"]["Tables"]["recurring_rules"]["Update"] & {
          start_date?: string;
          end_date?: string | null;
        };
        Relationships: GeneratedDatabase["public"]["Tables"]["recurring_rules"]["Relationships"];
      };
    };
    // archive_payment の Returns を number → boolean に変更するため Omit で上書き
    Functions: Omit<GeneratedDatabase["public"]["Functions"], "archive_payment"> & {
      archive_payment: {
        Args: { p_payment_id: string; p_user_id: string };
        Returns: boolean;
      };
    };
  };
};

// ============================================
// Role literal type override
// The DB CHECK constraint (role IN ('owner','member')) is not reflected
// in the generated types, so we override it here.
// ============================================
export type GroupMemberRole = "owner" | "member";

// ============================================
// Row types (utility aliases)
// ============================================
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Group = Database["public"]["Tables"]["groups"]["Row"];
export type GroupMember = Omit<
  Database["public"]["Tables"]["group_members"]["Row"],
  "role"
> & { role: GroupMemberRole };
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Payment = Database["public"]["Tables"]["payments"]["Row"];
export type PaymentSplit = Database["public"]["Tables"]["payment_splits"]["Row"];
export type DemoSession = Database["public"]["Tables"]["demo_sessions"]["Row"];

// ============================================
// Insert types
// ============================================
export type ProfileInsert = Database["public"]["Tables"]["profiles"]["Insert"];
export type GroupInsert = Database["public"]["Tables"]["groups"]["Insert"];
export type GroupMemberInsert = Omit<
  Database["public"]["Tables"]["group_members"]["Insert"],
  "role"
> & { role?: GroupMemberRole };
export type CategoryInsert = Database["public"]["Tables"]["categories"]["Insert"];
export type PaymentInsert = Database["public"]["Tables"]["payments"]["Insert"];
export type PaymentSplitInsert = Database["public"]["Tables"]["payment_splits"]["Insert"];
export type DemoSessionInsert = Database["public"]["Tables"]["demo_sessions"]["Insert"];

// ============================================
// Extended types with relations
// ============================================
export type PaymentWithDetails = Payment & {
  profiles: Profile;
  categories: Category | null;
  payment_splits: (PaymentSplit & { profiles: Profile })[];
};

export type GroupWithMembers = Group & {
  group_members: (GroupMember & { profiles: Profile })[];
};

// ============================================
// Settlement session status literal type
// (Migration 019 で追加)
// ============================================
export type SettlementSessionStatus =
  | "draft"
  | "confirmed"
  | "pending_payment"
  | "settled";

// ============================================
// Settlement session with typed columns
// (generated types の status は string, net_transfers は Json なのでリテラル型で補強)
// ============================================
export type SettlementSessionRow = {
  id: string;
  group_id: string;
  period_start: string;
  period_end: string;
  status: SettlementSessionStatus;
  created_by: string;
  created_at: string;
  confirmed_at: string | null;
  confirmed_by: string | null;
  net_transfers: NetTransfer[] | null;
  is_zero_settlement: boolean;
  payment_reported_at: string | null;
  payment_reported_by: string | null;
  settled_at: string | null;
  settled_by: string | null;
};

/** net_transfers JSONB の各要素型 */
export type NetTransfer = {
  from_id: string;
  from_name: string;
  to_id: string;
  to_name: string;
  amount: number;
};
