/**
 * Database types for Kakeibo Share
 *
 * - database.generated.ts: Auto-generated by `npx supabase gen types typescript --local`
 *   DO NOT edit manually. Regenerate with `npm run db:gen-types`.
 * - This file: Re-exports with overrides and helper types.
 */

export type { Json } from "./database.generated";
export type { Database } from "./database.generated";

// Re-import for local use
import type { Database } from "./database.generated";

// ============================================
// Role literal type override
// The DB CHECK constraint (role IN ('owner','member')) is not reflected
// in the generated types, so we override it here.
// ============================================
export type GroupMemberRole = "owner" | "member";

// ============================================
// Row types (utility aliases)
// ============================================
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Group = Database["public"]["Tables"]["groups"]["Row"];
export type GroupMember = Omit<
  Database["public"]["Tables"]["group_members"]["Row"],
  "role"
> & { role: GroupMemberRole };
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Payment = Database["public"]["Tables"]["payments"]["Row"];
export type PaymentSplit = Database["public"]["Tables"]["payment_splits"]["Row"];
export type Settlement = Database["public"]["Tables"]["settlements"]["Row"];
export type DemoSession = Database["public"]["Tables"]["demo_sessions"]["Row"];

// ============================================
// Insert types
// ============================================
export type ProfileInsert = Database["public"]["Tables"]["profiles"]["Insert"];
export type GroupInsert = Database["public"]["Tables"]["groups"]["Insert"];
export type GroupMemberInsert = Omit<
  Database["public"]["Tables"]["group_members"]["Insert"],
  "role"
> & { role?: GroupMemberRole };
export type CategoryInsert = Database["public"]["Tables"]["categories"]["Insert"];
export type PaymentInsert = Database["public"]["Tables"]["payments"]["Insert"];
export type PaymentSplitInsert = Database["public"]["Tables"]["payment_splits"]["Insert"];
export type SettlementInsert = Database["public"]["Tables"]["settlements"]["Insert"];
export type DemoSessionInsert = Database["public"]["Tables"]["demo_sessions"]["Insert"];

// ============================================
// Extended types with relations
// ============================================
export type PaymentWithDetails = Payment & {
  profiles: Profile;
  categories: Category | null;
  payment_splits: (PaymentSplit & { profiles: Profile })[];
};

export type GroupWithMembers = Group & {
  group_members: (GroupMember & { profiles: Profile })[];
};
